{% set name = "skutil" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d99a6bae7c7e29dbad5347e60c5fde7356a35cc80a1024b987ab514da853c5b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - decore
    - numpy >=1.13.3
    - scipy >=0.19.1
    - joblib >=0.11
    - threadpoolctl >=2.0.0
    - scikit-learn

test:
  requires:
    - python {{ python_min }}
  imports:
    - skutil

about:
  home: https://github.com/shaypal5/skutil
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Utilities for scikit-learn.

  description: |
    Utilities for scikit-learn.
  dev_url: https://github.com/shaypal5/skutil

extra:
  recipe-maintainers:
    - Silun
    - shaypal5
