{% set name = "skutil" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22e7ebd00dae483e371bc1723c70e4e90b7147d2ce68d920a3a60be05379216b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - decore
    - numpy >=1.13.3
    - scipy >=0.19.1
    - joblib >=0.11
    - threadpoolctl >=2.0.0
    - scikit-learn

test:
  imports:
    - skutil

about:
  home: https://github.com/shaypal5/skutil
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Utilities for scikit-learn.

  description: |
    Utilities for scikit-learn.
  dev_url: https://github.com/shaypal5/skutil

extra:
  recipe-maintainers:
    - Silun
    - shaypal5
